version: '3.4'

services:
  dualcontainer-api:
    image: ${DOCKER_REGISTRY-}dualcontainer-api
    build:
      context: .
      dockerfile: FitTalksDemo.DualContainer.API/Dockerfile
  
  dualcontainer-microdb:
    image: mcr.microsoft.com/mssql/server:2017-latest
