version: '3.4'

services:
  dualcontainer-api:
    container_name: dualcontainer-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:CustomerConnectionString=Server=dualcontainer-microdb;Database=CustomerDb;User Id =sa;Password=123456Seven
    depends_on:
      - dualcontainer-microdb
    ports:
      - "5055:80"
  
  dualcontainer-microdb:
    container_name: dualcontainer-microdb
    environment:
        SA_PASSWORD: "123456Seven"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "4040:1433"
